require("core.plugin_config.nvim-tree")
require("core.plugin_config.mason")
require("core.plugin_config.cmp")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp_config")
require("core.plugin_config.tabby")
require("core.plugin_config.comment")
